import type { OrgSelectionInvite } from './types'

export const mockOrgSelectionInvites: OrgSelectionInvite[] = [
  {
    id: 1,
    organizationName: 'Liga Metropolitana',
    role: 'ATHLETE',
    teamName: 'Campinas Hawks',
    jerseyNumber: 12,
    status: 'PENDING',
    sentAt: 'Enviado há 2 dias',
    expiresAt: 'Expira em 5 dias',
  },
  {
    id: 2,
    organizationName: 'Circuito Interior',
    role: 'COACHING_STAFF',
    teamName: 'Valinhos Court',
    jerseyNumber: null,
    status: 'PENDING',
    sentAt: 'Enviado ontem',
    expiresAt: 'Expira em 6 dias',
  },
  {
    id: 3,
    organizationName: 'Associação Quadra Sul',
    role: 'TEAM_ADMIN',
    teamName: 'Piracicaba Reds',
    jerseyNumber: null,
    status: 'PENDING',
    sentAt: 'Enviado hoje',
    expiresAt: 'Expira em 7 dias',
  },
  {
    id: 4,
    organizationName: 'Copa Norte Paulista',
    role: 'ORG_ADMIN',
    teamName: null,
    jerseyNumber: null,
    status: 'PENDING',
    sentAt: 'Enviado há 3 dias',
    expiresAt: 'Expira em 4 dias',
  },
  {
    id: 5,
    organizationName: 'Liga Vale do Paraíba',
    role: 'ATHLETE',
    teamName: 'Taubaté Wings',
    jerseyNumber: 8,
    status: 'PENDING',
    sentAt: 'Enviado há 4 dias',
    expiresAt: 'Expira em 3 dias',
  },
  {
    id: 6,
    organizationName: 'Circuito Baixada',
    role: 'COACHING_STAFF',
    teamName: 'Santos Harbor',
    jerseyNumber: null,
    status: 'PENDING',
    sentAt: 'Enviado há 5 dias',
    expiresAt: 'Expira em 2 dias',
  },
  {
    id: 7,
    organizationName: 'Associação Centro-Oeste',
    role: 'TEAM_ADMIN',
    teamName: 'Bauru Atlas',
    jerseyNumber: null,
    status: 'PENDING',
    sentAt: 'Enviado há 6 dias',
    expiresAt: 'Expira amanhã',
  },
  {
    id: 8,
    organizationName: 'Liga Serrana',
    role: 'ATHLETE',
    teamName: 'Jundiaí Wolves',
    jerseyNumber: 21,
    status: 'PENDING',
    sentAt: 'Enviado há 1 semana',
    expiresAt: 'Expira hoje',
  },
  {
    id: 9,
    organizationName: 'Quadra Leste',
    role: 'COACHING_STAFF',
    teamName: 'Mogi Falcons',
    jerseyNumber: null,
    status: 'PENDING',
    sentAt: 'Enviado há 8 dias',
    expiresAt: 'Expira em 12 horas',
  },
  {
    id: 10,
    organizationName: 'Conferência Sul',
    role: 'ATHLETE',
    teamName: 'Sorocaba Storm',
    jerseyNumber: 33,
    status: 'PENDING',
    sentAt: 'Enviado há 9 dias',
    expiresAt: 'Expira em 6 horas',
  },
]
