FROM node:22-alpine
ENV NODE_ENV=development
WORKDIR /home/node/app

COPY package*.json ./

RUN npm ci && chown -R node:node /home/node/app

COPY --chown=node:node . .

USER node
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
