services:
  web:
    container_name: tcc-web
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    restart: unless-stopped
